In [1]:
import pandas as pd
import re

import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv('/content/drive/MyDrive/Kuliah/Experiment 2/BERT/LEGALBERTNER-POS-PREV-NEXT-200.csv')
df

,text,labels
0,PUTUSAN . NOMOR : 1974 / Pid . Sus / 2012 / PN...,O O O O B_VERN I_VERN I_VERN I_VERN I_VERN I_V...
1,Pengadilan Negeri Jakarta Barat yang memeriksa...,O O O O O O O O O O O O O O O O O O O O O O O ...
2,"AGNES TRI AHADI Als ANAS , lahir di Jakarta , ...",B_DEFN I_DEFN I_DEFN I_DEFN I_DEFN I_DEFN O O ...
3,Terdakwa menolak didampingi oleh Penasehat Huk...,O O O O O O O
4,Pengadilan Negeri tersebut ;,O O O O
...,...,...
24510,- Bahwa yang menjadi tugas analisis dengan acc...,O O O O O O O O O O O O O O O O O O O O O O O O
24511,Bahwa saksi kenal dengan terdakwa Mulyatno Wib...,O O O O O B_DEFN I_DEFN O O O O O O O O O O O ...
24512,- Bahwa yang menjadi tugas Direktur Pemasaran ...,O O O O O O O O O O O O O O O O O O O O O O O ...
24513,- Bahwa Struktur pemberian kredit KMK Bank DKI...,O O O O O O O O O O O O O O O O O O O O O O O ...
24514,- Bahwa mekanisme perpanjangan dan penambahan,O O O O O O

In [8]:
labels = df['labels']

In [9]:
for i, label in labels.iteritems():
  if bool(re.search(r'\b(?!O\b)\w+\b', label)) != True:
    df = df.drop(i)

In [10]:
df = df.reset_index(drop=True)
df

,text,labels
0,PUTUSAN . NOMOR : 1974 / Pid . Sus / 2012 / PN...,O O O O B_VERN I_VERN I_VERN I_VERN I_VERN I_V...
1,"AGNES TRI AHADI Als ANAS , lahir di Jakarta , ...",B_DEFN I_DEFN I_DEFN I_DEFN I_DEFN I_DEFN O O ...
2,MENUNTUT : 1 Menyatakan terdakwa AGNES TRI AHA...,O O O O O B_DEFN I_DEFN I_DEFN I_DEFN I_DEFN O...
3,2 Menjatuhkan pidana terhadap terdakwa DERRY S...,O O O O O B_DEFN I_DEFN I_DEFN I_DEFN O O O O ...
4,"Menimbang , bahwa terdakwa didakwa dengan sura...",O O O O O O O O O O O O B_ARTV I_ARTV I_ARTV I...
...,...,...
7949,- Bahwa yang ditunjuk untuk melakukan site vis...,O O O O O O O O O O O O O O O O O O O O O O O ...
7950,Bahwa pada bagian III . Isi . MAK . No . 183 /...,O O O O O O O O O O O O O O O O O O O O O O O ...
7951,9 . Bahwa atas kredit PT Likotama Harum telah ...,O O O O O O O O O O O O O O O O O O O O O O O ...
7952,"Bahwa sepengetahuan saksi , pemberian kredit k...",O O O O O O O O O O O O O O O O O O O O O O O ...
7953,Bahwa saksi kenal dengan terdakwa Mulyatno Wib...,O O O O O B_DEFN I_DEFN O O O O O O O O O O O ...

In [11]:
df.to_csv('LegalNER NEW.csv', index=False)